/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mastermind;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
/**
 *
 * @author loicm
 */
public class FenetreAccueil extends javax.swing.JFrame {

    /**
     * Creates new form FenetreAccueil
     */
    public FenetreAccueil() {
        
        
        setTitle("Mastermind - Accueil");
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setLayout(new BorderLayout());
    setSize(600, 400);

    JLabel titre = new JLabel("MasterMind", JLabel.CENTER);
    titre.setFont(new Font("Bodoni MT Black", Font.BOLD , 100));
    add(titre, BorderLayout.NORTH);

    String reglesHtml = "<html><div style='text-align: center;'>"
        + "<b>Bienvenue dans MasterMind !</b><br><br>"
        + "Le but du jeu est de deviner la combinaison secrète composée de 4 couleurs.<br><br>"
        + "<b>Couleurs disponibles :</b> Rouge (R), Bleu (B), Vert (G), Jaune (Y),<br>"
        + "Orange (O), Violet (P).<br><br>"
        + "<b>Comment jouer :</b><br>"
        + " - Cliquez sur les boutons de la ligne active pour sélectionner une couleur.<br>"
        + " - Validez votre combinaison en appuyant sur le bouton <i>\"Valider\"</i>.<br>"
        + " - Analysez les indices pour ajuster vos tentatives.<br><br>"
        + "<b>Indices :</b><br>"
        + " - <b>Noir :</b> Une couleur correcte et bien placée.<br>"
        + " - <b>Blanc :</b> Une couleur correcte mais mal placée.<br><br>"
        + "<b>Fin de la partie :</b><br>"
        + "Vous gagnez si vous trouvez la combinaison en moins de 10 tentatives.<br>"
        + "Sinon, la partie est perdue.<br><br>"
        + "<b>Bonne chance et amusez-vous bien !</b>"
        + "</div></html>";

JLabel lblRegles = new JLabel(reglesHtml, SwingConstants.CENTER);
            
        
        lblRegles.setFont(new Font("Arial", Font.PLAIN, 22));
        this.getContentPane().add(lblRegles, BorderLayout.CENTER);;

    JButton btnOuvrir = new JButton("Ouvrir");
    btnOuvrir.setFont(new Font("Arial", Font.BOLD, 35));
    btnOuvrir.addActionListener(e -> {
        new MasterMindGUI().setVisible(true); // Lance la fenêtre de jeu
        dispose(); // Ferme la fenêtre d'accueil
    });
    add(btnOuvrir, BorderLayout.SOUTH);
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
